site_name: Vertex Animation Docs
theme:
  name: material
  logo: assets\icon_CrowdEditor_40x.png

nav:
    - Home: index.md
    - Quick Start Guide: quick-start.md

markdown_extensions:
  - attr_list
