site_name: Vertex Animation Toolset Docs
theme:
  name: material
  logo: assets/icon_CrowdEditor_40x.png
  palette:
    scheme: slate
    primary: blue grey
    accent: blue grey
  custom_dir: docs/stylesheets
extra_css:
  - stylesheets/extra.css

nav:
    - About the Plugin: index.md
    - Quick Start Guide: quick-start.md
    - Assets:
        - VA Asset Collection: va-asset-collection.md
        - VA Asset Editor: va-asset-editor.md
    - Animation System:
        - VA Player: va-animation-player.md
        - VA Lists: vertex-anim-lists.md
        - VA Logic: animation-logic.md
    - Components:
        - VA Mesh Component: vertex-anim-mesh-component.md
        - VA Instanced Mesh Component: vertex-anim-instanced-mesh-component.md
    - Crowd Tools:
        - Overview: crowd-tools-editor-mode.md
        - Crowd Brushes: crowd-brushes.md
        - Paint Tool: crowd-tools-paint.md
        - Grid Tool: crowd-tools-grid.md
        - Single Placement: crowd-tools-single.md
    - Troubleshooting: troubleshooting.md

markdown_extensions:
  - attr_list
