site_name: VAT Toolset Docs
theme:
  name: material
  logo: assets/icon_CrowdEditor_40x.png
  palette:
    scheme: slate
    primary: blue grey
    accent: blue grey
  custom_dir: docs/stylesheets
extra_css:
  - stylesheets/extra.css

nav:
    - About the Plugin: index.md
    - Quick Start Guide: quick-start.md
    - Workflow Overview: workflow-overview.md
    - Assets:
        - VA Asset Collection: va-asset-collection.md
        - VA Asset Editor: va-asset-editor.md
        - VA Editor - Animation Settings: va-asset-editor-animation.md
        - VA Editor - Mesh Settings: va-asset-editor-mesh.md
        - VA Editor - Custom Data: va-asset-editor-custom-data.md
    - Animation System:
        - VA Animation Player: va-animation-player.md
        - VA Animation Lists: vertex-anim-lists.md
        - VA Animation Logic: animation-logic.md
    - Components:
        - VA Mesh Component (Single): vertex-anim-mesh-component.md
        - VA Instanced Mesh Component (Multiple): vertex-anim-instanced-mesh-component.md
    - Crowd Tools:
        - Editor Mode Overview: crowd-tools-editor-mode.md
        - Crowd Brushes: crowd-brushes.md
        - Placement Methods:
            - Paint Tool: crowd-tools-paint.md
            - Grid Tool: crowd-tools-grid.md
            - Single Placement: crowd-tools-single.md
        - Keyboard Shortcuts: crowd-tools-keyboard-shortcuts.md
    - Troubleshooting: troubleshooting.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
