site_name: Vertex Animation Toolset Docs
theme:
  name: material
  logo: assets\icon_CrowdEditor_40x.png
  palette:
    scheme: slate
    primary: blue grey
    accent: blue grey
  custom_dir: docs/stylesheets
extra_css:
  - stylesheets/extra.css

nav:
    - About the Plugin: index.md
    - Quick Start Guide: quick-start.md

markdown_extensions:
  - attr_list
