site_name: Vertex Animation Toolset Docs
theme:
  name: material
  logo: assets/icon_CrowdEditor_40x.png
  palette:
    scheme: slate
    primary: blue grey
    accent: blue grey
  custom_dir: docs/stylesheets
extra_css:
  - stylesheets/extra.css

nav:
    - About the Plugin: index.md
    - Quick Start Guide: quick-start.md
    - Assets:
        - Vertex Anim Asset: vertex-animation-asset.md
        - Vertex Asset Editor: asset-editor.md
    - Animation System:
        - Vertex Anim Lists: vertex-anim-lists.md
        - Animation Logic: animation-logic.md
    - Components:
        - Vertex Anim Mesh Component: vertex-anim-mesh-component.md
        - Vertex Anim Instanced Mesh Component: vertex-anim-instanced-mesh-component.md
    - Crowd Tools:
        - Editor Mode: crowd-tools-editor-mode.md
        - Navigation Tools: crowd-tools-navigation.md
        - Crowd Brushes: crowd-brushes.md
    - Troubleshooting: troubleshooting.md

markdown_extensions:
  - attr_list
